### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/evaluacion-intermedia-modulo-1-srojasz#2]
Muy buen trabajo!!!

Aquí tienes unos consejos para mejorar tu ejercicio:

Score: 39 / 45
- [x] HTML > HTML: Pon un buen título a la página.
- [x] HTML > LINK: El fichero de fuentes debe estar antes que nuestro fichero de estilos para que ningún fichero de estilos externo sobre escriba los nuestros.
- [x] HTML > MENÚ: Los textos de los enlaces deben ser "Blog" y "Contacto" en el HTML. Debemos ponerlos en mayúsculas con CSS.
- [x] HTML > MENÚ: Los enlaces deben tener el atributo `title`.
- [x] HTML > HTML: El contenido exacto del h1 debe ser "Creando diversidad digital". Debemos poner las primeras letras en mayúsculas con CSS.
- [x] CSS > PADDING y MARGIN: El padding de los enlaces no debería ser 0. Auméntalo para aumentar el área clickable, pero manteniendo los requisitos del diseño.

Es posible que cuando corrijas uno de estos puntos, otros se corrijan solos, ya que unos dependen de otros.

Y recuerda algo muy importante:

- Escribe todas las clases CSS en inglés.
- Escribe todos los ficheros y carpetas en inglés.
- Los commits tambien tienen que ser en inglés empezando por un verbo en infinitivo.

Ánimo y si tienes cualquier duda avísame!!!

> Este issue ha sido creado automáticamente por ello puede tener algún error, si hay algo que no te enjaca dímelo cuanto antes por favor.

**Comment by srojasz** [comment]
Hola Miguel, ayer hice los cambios que me sugerías :) Gracias
